version: "3.8"

services:
    mysql:
        image: mysql:8
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: testdb
        ports:
            - "3306:3306"
        volumes:
            - ./init/mysql:/docker-entrypoint-initdb.d

    postgres:
        image: postgres:14-alpine
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: testdb
        ports:
            - "5432:5432"
        volumes:
            - ./init/postgres:/docker-entrypoint-initdb.d

    redis:
        image: redis:6
        ports:
            - "6379:6379"

    kafka:
        image: confluentinc/cp-kafka:7.8.0
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_LISTENERS: PLAINTEXT://:9092
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
            KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
        ports:
            - "9092:9092"

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.17.1
        environment:
            - discovery.type=single-node
            - xpack.security.enabled=false
            - ES_JAVA_OPTS=-Xms512m -Xmx512m
        ports:
            - "9200:9200"
        mem_limit: 2g
        volumes:
            - ./init/elasticsearch:/usr/share/elasticsearch/init
        command: >
            /bin/bash -c "
            if [ ! -f /usr/share/elasticsearch/.initialized ]; then
                while ! curl -s http://localhost:9200 > /dev/null; do sleep 1; done;
                for f in /usr/share/elasticsearch/init/*.json; do
                    curl -X PUT 'http://localhost:9200/_index_template/template_1' -H 'Content-Type: application/json' -d @$$f
                done
                touch /usr/share/elasticsearch/.initialized
            fi
            & /usr/local/bin/docker-entrypoint.sh elasticsearch-node"

    jaeger:
        image: jaegertracing/all-in-one:latest
        ports:
            - "14268:14268" # collector
            - "16686:16686" # web UI
        environment:
            - COLLECTOR_OTLP_ENABLED=true
