environment: development

server:
    port: 8080
    read_timeout: 15
    write_timeout: 15
    idle_timeout: 60

mysql:
    host: localhost
    port: 3306
    user: root
    password: password
    database: testdb
    max_open_conns: 25
    max_idle_conns: 5
    max_lifetime: 5    # minutes
    max_idle_time: 5   # minutes

postgresql:
    host: localhost
    port: 5432
    user: postgres
    password: password
    database: testdb
    max_open_conns: 25
    max_idle_conns: 5
    max_lifetime: 5    # minutes
    max_idle_time: 5   # minutes

redis:
    host: localhost
    port: 6379
    pool_size: 10    # default pool size for development

kafka:
    brokers:
        - localhost:9092
    topic: events

elasticsearch:
    url: http://localhost:9200

tracing:
    enabled: true
    serviceName: "testcontainers-demo"
    collectorUrl: "localhost:4318"
    samplingRatio: 1.0
