environment: development

server:
    port: 8080

mysql:
    host: localhost
    port: 3306
    user: root
    password: password
    database: testdb

postgresql:
    host: localhost
    port: 5432
    user: postgres
    password: password
    database: testdb

redis:
    host: localhost
    port: 6379

kafka:
    brokers:
        - localhost:9092
    topic: events

elasticsearch:
    url: http://localhost:9200
