environment: development

mysql:
    host: localhost
    port: 3306
    user: root
    password: password
    database: testdb

postgres:
    host: localhost
    port: 5432
    user: postgres
    password: password
    database: testdb

redis:
    host: localhost
    port: 6379

kafka:
    brokers:
        - localhost:9092
    topic: test-topic

elasticsearch:
    url: http://localhost:9200
