environment: test

server:
    port: 8081
    read_timeout: 15
    write_timeout: 15
    idle_timeout: 60

mysql:
    host: localhost
    port: 3307
    user: test
    password: test
    database: testdb

postgresql:
    host: localhost
    port: 5433
    user: test
    password: test
    database: testdb

redis:
    host: localhost
    port: 6380
    pool_size: 5     # smaller pool size for testing

kafka:
    brokers:
        - localhost:9093
    topic: test-events

elasticsearch:
    url: http://localhost:9201

tracing:
    enabled: false
    serviceName: "testcontainers-demo-test"
    collectorUrl: "localhost:4318"
    samplingRatio: 1.0

# Test-specific settings
test:
    cleanup_enabled: true
    retry_attempts: 3
    retry_delay: 1s
    parallel_tests: true
