environment: test

server:
    port: 8081 # Different port for test environment

mysql:
    host: localhost
    port: 33306 # Different port for test environment
    user: test
    password: test
    database: testdb

postgresql:
    host: localhost
    port: 35432 # Different port for test environment
    user: test
    password: test
    database: testdb

redis:
    host: localhost
    port: 36379 # Different port for test environment

kafka:
    brokers:
        - localhost:39092 # Different port for test environment
    topic: test-events

elasticsearch:
    url: http://localhost:39200 # Different port for test environment

# Test-specific settings
test:
    cleanup_enabled: true
    retry_attempts: 3
    retry_delay: 1s
    parallel_tests: true
